# Legged model configuration for Go2 robot
verbose: false

urdfPath: /root/code/go2_ws/src/legged_model/urdf/go2.urdf

baseName: base
contact3DofNames:
  - FR_foot
  - FL_foot
  - RR_foot 
  - RL_foot

contact3DofPossInit:
  [0.1934, -0.142, 0,
  0.1934, 0.142, 0,
  -0.1934, -0.142, 0,
  -0.1934, 0.142, 0]

contact6DofNames: []

hipNames:
  - FR_thigh_joint
  - FL_thigh_joint
  - RR_thigh_joint
  - RL_thigh_joint 

jointOrder:
  - FR_hip_joint 
  - FR_thigh_joint
  - FR_calf_joint
  - FL_hip_joint
  - FL_thigh_joint
  - FL_calf_joint
  - RR_hip_joint
  - RR_thigh_joint
  - RR_calf_joint
  - RL_hip_joint
  - RL_thigh_joint
  - RL_calf_joint

qj_min:
  [-1.0472, -0.2094, -2.7227,
  -1.0472, -0.2094, -2.7227,
  -1.0472, -0.2094, -2.7227,
  -1.0472, -0.2094, -2.7227]
qj_max:
  [1.0472,  1.9897, -0.83776,
    1.0472,  1.9897, -0.83776,
    1.0472,  1.9897, -0.83776,
    1.0472,  1.9897, -0.83776]

tau_max:
  [23.7, 23.7, 45.43, 
  23.7, 23.7, 45.43, 
  23.7, 23.7, 45.43, 
  23.7, 23.7, 45.43]

# stanceIk:
  # - z: 0.35
  #   pitch: [-0.20, 0.20]
  #   roll: [-0.85, 0.85]
  
